# Generated by Django 5.1.1 on 2024-09-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('month', 'year')},
        ),
        migrations.AlterModelTable(
            name='budget',
            table='budget',
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
    ]
